### ISSUE TITLE
Implement a more intuitive UI for selecting TV show episodes

### ISSUE THREAD

**Issue by macjabeth** [macjabeth/showbunny#27]
At the moment it uses `prompt()` to gather this information. It could be better, and I welcome any contributors.

**Comment by bennetthanna** [comment]
Hello, I would be interested in trying my hand at this if no one else has claimed it!

**Comment by macjabeth** [comment]
@bennetthanna Of course!

**Comment by bennetthanna** [comment]
@macjabeth I put in a PR for this with some screenshots of what it looks like, whenever you get a moment to check it out. I'm open to any and all feedback! Thank you

**Comment by macjabeth** [comment]
@bennetthanna Just looked it over - great job! I think there are a few small issues with the styling consistency, but it's nothing that can't be addressed later on. I'll go ahead and merge it. Thank you!
