### ISSUE TITLE
Responsive Image Sizes

### ISSUE THREAD

**Issue by macjabeth** [macjabeth/showbunny#33]
Instead of coding the image URL as a background, it should use an `picture` tag with `source` tags set to appropriate poster sizes so that the image quality is optimized for each device.

Example:

```html
<picture>
  <source media="(max-width: 92px)" srcset="w92.jpg">
  <source media="(max-width: 154px)" srcset="w154.jpg">
  <source media="(max-width: 185px)" srcset="w185.jpg">
  <source media="(max-width: 342px)" srcset="w342.jpg">
  <source media="(max-width: 500px)" srcset="w500.jpg">
  <source media="(max-width: 780px)" srcset="w780.jpg">
  <img src="original.jpg" alt="Poster image">
</picture>
```

The available poster sizes can be viewed [here](https://api.themoviedb.org/3/configuration?api_key=fa4fa1ba075a48db1aeb756f4343bc23).
Documentation on responsive images can be found [here](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images).

**Comment by rahulshawdev** [comment]
Can you explain it briefly??

**Comment by d4rkener** [comment]
Ok
