### ISSUE TITLE
Need a responsive navigation bar for easy access of the website's resources

### ISSUE THREAD

**Issue by ARJITMALIK** [macjabeth/showbunny#36]
Hey @macjabeth , I think you should add a neat navigation bar on your website for easier navigation through movies/shows.

If you want I will make a nice and responsive floating navigation bar for your website using css with bootstrap 5 😃😃

**Comment by macjabeth** [comment]
Hey @ARJITMALIK!

That is a fantastic idea, and would be extremely appreciated.

However, for this project, we are attempting to avoid using any frameworks (such as Bootstrap) and instead rely on vanilla CSS and JavaScript to complete tasks. As such, it provides an interesting challenge and learning experience.

Some other things to note:

I'd like to have separate sections developed using web components. This brings a lot of advantages in terms of maintenance and reusability.

I'd also ask that you adopt [this concept](https://www.behance.net/gallery/115532245/Responsive-Anime-Website-Design-Concept) as inspiration for the design, as it's what I'm using for the rest of the site.

So, if you're up to the challenge, go ahead and take it away! Please add your changes to a feature branch and make your PR to the `rebirth` branch.

(PS. _Love_ the profile pic of Naruto in sage mode!)

**Comment by ARJITMALIK** [comment]
Alright, I would love to work on web components btw thanks for the compliment on my profile, DATTEBAYO!✌️

**Comment by macjabeth** [comment]
> Alright, I would love to work on web components

Hey @ARJITMALIK - just wanted to give a heads up if you're working on this, I added in an example of a working web component for the movie posters. Feel free to look it over and use it as inspiration for the navbar. 🙂 

Thanks again for taking this on! And, if you're interested, I'll be streaming more live development of this site on my [Twitch](https://www.twitch.tv/macjabeth) channel tomorrow at 2 p.m. CDT.

**Comment by ARJITMALIK** [comment]
That would be a great help, thanks for your efforts✌️😊

**Comment by ARJITMALIK** [comment]
Morning @macjabeth , please take a look into my modifications

- modified navigation bar
- set some google fonts 
- made the header sticky
- added some basic simple animations

I have created a pull request for the same to your develop branch.

And thanks again for providing this opportunity , got to learn a bunch of new techniques to stylize using CSS. 😃😃

**Comment by macjabeth** [comment]
Thanks for the PR, @ARJITMALIK! I merged it in last weekend.

While reviewing it however, I noticed it wasn't responsive on mobile screens, so it needed some modifications before I could push it to the live site. I also removed the search bar (for now) until we're ready to implement a site-wide search feature.

Feel free to join our Discord for more discussion on Showbunny and other topics. 🙂

**Comment by ARJITMALIK** [comment]
Yeah sure, I will look into that ✌️
