### ISSUE TITLE
Mobile images served with low resolution

### ISSUE THREAD

**Issue by macjabeth** [macjabeth/showbunny#54]
**Describe the bug**

Image natural dimensions should be proportional to the display size and the pixel ratio to maximize image clarity.

**To Reproduce**

1. Load site on mobile device
2. See pixelated/unclear images

**Expected behavior**

Load the correct image size from the API to sharpen image resolution.

**Screenshots**

<img width="591" alt="Screen Shot 2021-09-14 at 12 20 58 AM" src="https://user-images.githubusercontent.com/8473052/133199375-a2374b9e-6995-49a0-81a3-12b0bcc6d884.png">

**Comment by manshu07** [comment]
I think you have to upload original image with high DPi. Then issue will resolved. I didn't find your current image high resolution.
