### ISSUE TITLE
Have default sources pull from the weekly trending items via TMDB

### ISSUE THREAD

**Issue by macjabeth** [macjabeth/showbunny#9]
As per: https://developers.themoviedb.org/3/trending/get-trending

Ideally, it should pull the trending movies for the week upon loading the site; if one switches to the TV tab (next to the search bar), it should then pull trending TV shows for the week.

**Comment by shad-k** [comment]
@macjabeth I'll work on this issue.

**Comment by macjabeth** [comment]
@shad-k Wonderful, thank you!

**Comment by shad-k** [comment]
@macjabeth made a PR. Let me know what you think about it.

**Comment by macjabeth** [comment]
@shad-k It looks good! However, I noticed a bug with the pagination. It doesn't seem to load due to it using the cached first page results before it can fetch the new data. Do you think you find a workaround for that?

**Comment by macjabeth** [comment]
@shad-k It seemed like a simple enough fix, so I went ahead and pushed it through for you. It works wonderfully. Thank you so much!
